[project]
name = "s1-modbus"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pymodbus==2.5.3",
    "termcolor>=3.1.0",
    "twisted>=25.5.0",
]
